
.TH 6005_CW1_2012 1 "23 February 2012" "Version 0.1" 

.\"=====================================================================
.SH NAME
6005_CW1_2012 \- PHP RSS Reader for INFO6005
.SH SYNOPSIS
.B info6005-cw1-sk11g08 [--feeds feed1[,feed2,...] --items n] 
.SH DESCRIPTION
.PP 
This software displays a defined number of RSS elements from specified RSS feeds
.SH OPTIONS
.PP
.IP "\-\-feeds feed1[,feed2,...]"
list of URI's to read from
.PP
.IP "\-\-items n" 
number of items to read

.SH FILES
.I /etc/info6005-cw1-sk11g08/feeds.conf
Global feed configuration file

.SH BUGS
No known bugs

.SH AUTHOR
.B Samantha Kanza (sk11g08@ecs.soton.ac.uk)

.SH SEE ALSO
.I https://github.com/samikanza/6005_cw1_2012
